spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: krastavici
    username: root
    url: jdbc:mysql://localhost:3306/likebook?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
server:
  port: 8080
